language: python
python: '3.6'
dist: bionic

cache: pip

services:
  - postgresql

before_install:
  - pip install https://github.com/ome/zeroc-ice-ubuntu1804/releases/download/0.3.0/zeroc_ice-3.6.5-cp36-cp36m-linux_x86_64.whl
  - pip install -r dev-requirements.txt
  - pushd ..
  - wget -q https://downloads.openmicroscopy.org/omero/5.6.1/artifacts/OMERO.server-5.6.1-ice36-b225.zip && unzip -q OMERO.server-5.6.1-ice36-b225.zip && ln -s OMERO.server-5.6.1-ice36-b225 OMERO.server
  - popd

install:
  - pre-commit run --all-files
  - pip install .

script:
  # To run the integration tests locally set
  #   OMERODIR=/path/to/OMERO.server
  # Optionally set:
  #   POSTGRES_HOST=postgres.server
  #   POSTGRES_USER=admin-user
  #   POSTGRES_PASSWORD=admin=password
  - export OMERODIR=$PWD/../OMERO.server
  - pytest --cov=omero_database

deploy:
  - provider: pypi
    # Remove for deployment to official PyPi repo
    server: https://test.pypi.org/legacy/
    user: __token__
    # password: $PYPI_PASSWORD
    distributions: sdist bdist_wheel
    on:
      tags: true
